### ISSUE TITLE
Please update main branch (stopped at 11 Jun 2024)

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#1343]
> `error CS9240: Target runtime doesn't support by-ref-like generics.`

```cs
using System;

void M<T>(T disposable) where T : IDisposable, allows ref struct
{
    disposable.Dispose();
}
```

https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfAAQCYBGAWAChKCAWAAgFkAeAFQD4AKFugEygGcADgHt+EYABtUASjoB3ABYZUdbiDoBJACICRYyajh0IEicLn866VFjr8E6AK4BjBJQDelOt967R4qQA6HSFRVA5pAG5KAF8gA

**Comment by John0King** [comment]
any progress on this ?

**Comment by jnm2** [comment]
@ashmind It seems that very shortly after the last fix you did to get main updating again, it froze again.

**Comment by julealgon** [comment]
I wanted to test some code using the new `OverloadResolutionPriority` attribute and hit the same limitation 😢

**Comment by chillitom** [comment]
dotnet 9/ C# 13 is out, would be great to have it included

**Comment by ashmind** [comment]
This is now resolved, thanks for reporting.

**Comment by KeterSCP** [comment]
Hi @ashmind! The new syntax is available only on `main` branch. But for `Default`/`X64` it is still not updated. Is this expected?
